# Generated by Django 5.2.4 on 2026-07-31 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category_type', models.CharField(choices=[('THEME', 'Theme'), ('REGION', 'Region'), ('COUNTRY', 'Country'), ('TYPE', 'Story Type')], default='THEME', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Material icon name for the category', max_length=50)),
                ('color', models.CharField(default='#C85A32', help_text='Hex color code for the category', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(help_text='Short summary for story cards', max_length=500)),
                ('content', models.TextField(help_text='Full story content (supports Markdown)')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('culture', models.CharField(blank=True, help_text='Cultural group or tradition', max_length=150)),
                ('language_original', models.CharField(blank=True, help_text='Original language of the story', max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/covers/')),
                ('audio_file', models.FileField(blank=True, help_text='Audio narration of the story', null=True, upload_to='stories/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])])),
                ('video_file', models.FileField(blank=True, help_text='Video content for the story', null=True, upload_to='stories/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Estimated reading/listening time in seconds', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_stories', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='stories', to='stories.category')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=20)),
                ('file', models.FileField(upload_to='stories/media/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='stories.story')),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('SUMMARY', 'AI Summary'), ('TRANSLATION', 'AI Translation'), ('QUIZ', 'AI Quiz'), ('HISTORICAL_CONTEXT', 'Historical Context'), ('CULTURAL_NOTE', 'Cultural Note')], max_length=30)),
                ('content', models.TextField(help_text='AI-generated content')),
                ('model_used', models.CharField(blank=True, help_text='Which AI model generated this content', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether a human reviewer has verified this content')),
                ('language', models.CharField(default='en', help_text='ISO 639-1 language code', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content', to='stories.story')),
            ],
            options={
                'verbose_name': 'AI Content',
                'verbose_name_plural': 'AI Content',
                'ordering': ['content_type'],
                'unique_together': {('story', 'content_type', 'language')},
            },
        ),
    ]
