# Generated by Django 5.2.4 on 2026-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video_generation_id',
            field=models.CharField(blank=True, help_text='Luma AI generation ID for tracking video generation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='video_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Current status of AI video generation', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of the generated AI video', null=True),
        ),
    ]
