# Generated by Django 5.2.4 on 2026-08-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_video_generation_id_story_video_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blurhash',
            field=models.CharField(blank=True, help_text='BlurHash placeholder for progressive image loading', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StoryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('CULTURAL_INACCURACY', 'Cultural Inaccuracy'), ('INAPPROPRIATE_CONTENT', 'Inappropriate Content'), ('FACTUAL_ERROR', 'Factual Error'), ('OFFENSIVE_LANGUAGE', 'Offensive Language'), ('COPYRIGHT_ISSUE', 'Copyright Issue'), ('OTHER', 'Other')], max_length=30)),
                ('comments', models.TextField(blank=True, help_text='Additional details about the feedback')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story Feedback',
                'verbose_name_plural': 'Story Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
