# Generated by Django 5.2.4 on 2026-07-31 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique identifier encoded in the QR code', max_length=32, unique=True)),
                ('artifact_name', models.CharField(help_text='Name of the physical museum artifact', max_length=200)),
                ('artifact_description', models.TextField(blank=True, help_text='Description of the artifact')),
                ('museum_location', models.CharField(blank=True, help_text='Location within the museum (e.g., Gallery A, Shelf 3)', max_length=200)),
                ('artifact_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/artifacts/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the QR code', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(help_text='Story linked to this QR code', on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='stories.story')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='qr_codes.qrcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Scan Log',
                'verbose_name_plural': 'QR Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
